### ISSUE TITLE
Hardcoded path for s:JumpCommand

### ISSUE THREAD

**Issue by logankoester** [padde/jump.vim#1]
I haven't installed this yet to give it a spin, but it looks like there might be an issue with https://github.com/padde/jump.vim/blob/master/plugin/jump.vim#L16 hardcoding the path to `autojump.bash`.

On my (Arch Linux) system, autojump.bash is located at `/etc/profile.d/autojump.bash` rather than `/usr/local/etc/autojump.bash`.

I suppose I could override this in `.vimrc`, so not a dealbreaker. Just something to be aware of.

Otherwise, very nice!

**Comment by juanedi** [comment]
This is an issue indeed.

On a recent installation of autojump (22.3.0 installed via Homebrew on OSX) the path changed to `/usr/local/etc/autojump.sh` and the plugin suddenly stoped working (I ended up creating a symlink to work around the problem).

Besides providing a way to override it, I'm not sure if there is a way to infer the location of the script.

**Comment by padde** [comment]
@logankoester @juanedi sorry I took so long. I just fixed this issue by auto-detecting the executable in common locations and making it configurable in case that doesn't work. Would you please give it a try and see if it works for you?

**Comment by padde** [comment]
jump.vim currently checks [the following paths](https://github.com/padde/jump.vim/blob/f346b099723d595d81220a753e4b339f6382afb4/plugin/jump.vim#L7-L15) for the executable, please let me know if anything is missing or open a PR.

**Comment by logankoester** [comment]
Thanks for reminding me that autojump exists, somehow it fell out of my workflow after years of daily use. :racing_car:
